#!/usr/bin/env bash
# Installs, configures, and starts the load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo chmod 666 /etc/haproxy/haproxy.cfg
echo "\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend backend-servers

backend backend-servers
    balance roundrobin
    server 326010-web-01 54.157.131.6:80 check
    server 326010-web-02 18.214.88.110:80 check
    " >> /etc/haproxy/haproxy.cfg

sudo sed -i 's/^ENABLED=./ENABLED=1/' /etc/default/haproxy

sudo service haproxy restart
